### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by dropitlikecross** [fzwoch/mix-mox#2]
Any instructions on the use?

**Comment by fzwoch** [comment]
Not really :-)

Assuming you got it to build and started, a window pops up and asks for a channel name. You enter it and it should start playing if the channel is online.

Pressing "H" will pop up a small dialog with some key shortcuts. It is a very simple and basic app. Don't expect too much here - its main purpose is to run it on hardware decoders which are not available on Linux browsers.
